# Generated by Django 5.2.8 on 2025-12-13 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applicantapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional course code (e.g., CS, IT, BA)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Course',
                'verbose_name_plural': 'Academic Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicantapp.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='company_logos/default.png', upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ManyToManyField(related_name='applied_posts', through='Companyapp.Application', to='Applicantapp.applicant')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Companyapp.department')),
                ('required_courses', models.ManyToManyField(help_text='Academic courses/programs that qualify someone for this position', related_name='posts', to='Companyapp.academiccourse')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvertised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('min_experience_years', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required')),
                ('required_education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD')], default='Bachelor', max_length=50)),
                ('required_skills', models.TextField(default='', help_text='Comma-separated skills (e.g. Python, Django, SQL)')),
                ('deadline', models.DateTimeField()),
                ('max_applicants', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_adverts', to='Companyapp.department')),
                ('selected_courses', models.ManyToManyField(help_text='Academic courses accepted for this specific job vacancy', related_name='job_advertisements', to='Companyapp.academiccourse')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_adverts', to='Companyapp.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companyapp.post'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'post')},
        ),
    ]
