# Generated by Django 5.2.8 on 2025-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g., smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_password_encrypted',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='Usually 587 for TLS'),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
