# Generated by Django 5.2.8 on 2025-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0004_remove_jobadvertised_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvertised',
            name='keywords',
        ),
        migrations.AddField(
            model_name='jobadvertised',
            name='min_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AddField(
            model_name='jobadvertised',
            name='required_education',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD')], default='Bachelor', max_length=50),
        ),
        migrations.AddField(
            model_name='jobadvertised',
            name='required_skills',
            field=models.TextField(default='', help_text='Comma-separated skills (e.g. Python, Django, SQL)'),
        ),
    ]
