# Generated by Django 5.2.8 on 2025-12-05 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0005_remove_jobadvertised_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional course code (e.g., CS, IT, BA)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Course',
                'verbose_name_plural': 'Academic Courses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobadvertised',
            name='selected_courses',
            field=models.ManyToManyField(help_text='Academic courses accepted for this specific job vacancy', related_name='job_advertisements', to='Companyapp.academiccourse'),
        ),
        migrations.AddField(
            model_name='post',
            name='required_courses',
            field=models.ManyToManyField(help_text='Academic courses/programs that qualify someone for this position', related_name='posts', to='Companyapp.academiccourse'),
        ),
    ]
